# Generated by Django 2.0.1 on 2018-01-27 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_num', models.IntegerField(default=0)),
                ('children_num', models.IntegerField(default=0)),
                ('Family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Simcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('appartment_num', models.IntegerField(default=0)),
                ('Family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.City')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Street'),
        ),
    ]
