# Generated by Django 2.0.1 on 2018-01-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='Family',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='simcha',
            old_name='Family',
            new_name='family',
        ),
    ]
