# Generated by Django 2.0.1 on 2018-01-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20180128_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='building',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
